### PR TITLE
#234 Separate tinychain.async python package out of tinychain

### PR DESCRIPTION
**Pull request by RohanKaushikan**

### CODE REVIEW

**Review by haydnv — CHANGES_REQUESTED** [review]
The client tests now pass! There are still some changes needed before this can be merged in though because this won't be an installable Python package until it has a setup.cfg file.
 1. copy the "metadata" section from the setup.cfg file in the client package [here](https://github.com/haydnv/tinychain/blob/main/client/setup.cfg) and update the description to state what this package does (it provides an asychronous implementation of a `Host`)
 1. also update the README to state what this package does/what functionality it provides
 1. remove the LICENSE file since it's already provided at the root of the repo
 1. rename the "tinychain.async" directory to "client-async" to disambiguate it from other asynchronous functionality
 1. test that your changes work by running `pip3 install -e tinychain.async` and fix any configuration bugs you find (I believe this will require renaming the "src" directory to "tinychain.async")

**Comment by RohanKaushikan** [comment]
Understood. I'll make these changes and get back to you shortly.

**Comment by haydnv** [comment]
Almost there! A few pointers:
 - the `...egg_info` directory is a build artifact and doesn't belong in the Git repo. You can delete the directory and copy the [.gitignore file](https://github.com/haydnv/tinychain/blob/main/client/.gitignore) from the `client` directory to prevent this from happening again.
 - the package configuration files (`README.md`, `pyproject.toml`, `setup.cfg`) go *outside* the source code directory (you can see an example of this in the [client] directory)
 - I realized when I was testing this that "async" is a reserved keyword, so "tinychain.async" is not a valid package name--my bad! You can use "tinychain_async" instead

The package can now be built and installed using `pip3 install -e`--good work! There's still one major problem though: how can anyone use the code in asynchronous.py?

```bash
$ python3 -c "import tinychain_async"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.../tinychain/client-async/tinychain_async/__init__.py", line 1, in <module>
    from .asynchronous import Host, Local
  File "/.../tinychain/client-async/tinychain_async/asynchronous.py", line 5, in <module>
    from ..context import to_json
ImportError: attempted relative import beyond top-level package
```

Hint: since you moved the code outside the "tinychain" package, relative imports don't work anymore--try `from tinychain.<module name> import ..." instead

**Comment by haydnv** [comment]
Closing this since it's covered by #280

**Pull request closed without merging**
