### PR TITLE
test initializing a complex number

### PR DESCRIPTION
**Pull request by haydnv**

### CODE REVIEW

**Comment by haydnv** [comment]
@mukahraman I fixed the tests but you'll need to run a local Docker container in order to see several of the fixes. Do you know why `assert np.arctan(3 / 4) == np.angle(3 + 4j)` doesn't work?

**Comment by mukahraman** [comment]
@haydnv some tests are giving me error when I use docker container that I ran with
`docker run -it -p 8702:8702/tcp $(docker build https://github.com/haydnv/tinychain.git#complex_numbers -q) ./tinychain --address=0.0.0.0`
I have also changed the `base.py` accordingly. Is it normal?

**Comment by haydnv** [comment]
@mukahraman thanks Mustafa! Some thoughts:
 - you can set the `TC_HOST` environment var like so: `export TC_HOST=http://127.0.0.1:8702` to avoid changing base.py
 - you can run `python3 -m tests.tctest.client -k ComplexTensorOpsTests` to avoid changing any import statements
 - `np.arctan2` and `np.angle` don't agree for me (I'm sure there's a good reason, I just don't understand what it is):

```bash
$ ipython3 
...
In [1]: import numpy as np

In [2]: np.arctan2(3, 4)
Out[2]: 0.6435011087932844

In [3]: np.angle(3 + 4j)
Out[3]: 0.9272952180016122

```

Consider also adding some tests for complex sparse tensors (you can see examples for real sparse tensors in the `test_tensor.py` files).

**Comment by mukahraman** [comment]
Thank you @haydnv. For the arctan2 you can use it like `np.arctan2(n.imag, n.real)` it should work.

**Comment by mukahraman** [comment]
@haydnv I am still getting errors. What am I missing?

```docker run -it -p 8702:8702/tcp $(docker build https://github.com/haydnv/tinychain.git#complex_numbers -q) ./tinych
ain --address=0.0.0.0

export TC_HOST=http://127.0.0.1:8702

$ python3 -m tctest.client -k ComplexNumberOpsTests
FEE...EE...E..
======================================================================
ERROR: testAngle (tctest.client.test_complex.ComplexNumberOpsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mustafa/git/tc/tests/tctest/client/test_complex.py", line 37, in testAngle
    actual = self.host.post(ENDPOINT, cxt)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 113, in post
    return self._handle(request)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 54, in _handle
    raise NotFound(response)
tinychain.error.NotFound: {'/error/not_found': 'while resolving z_subject_subject_subject: /imag'}

======================================================================
ERROR: testConjugate (tctest.client.test_complex.ComplexNumberOpsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mustafa/git/tc/tests/tctest/client/test_complex.py", line 46, in testConjugate
    actual = self.host.post(ENDPOINT, cxt)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 113, in post
    return self._handle(request)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 54, in _handle
    raise NotFound(response)
tinychain.error.NotFound: {'/error/not_found': 'while resolving z.1_subject: /imag'}

======================================================================
ERROR: testExp (tctest.client.test_complex.ComplexNumberOpsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mustafa/git/tc/tests/tctest/client/test_complex.py", line 141, in testExp
    actual = self.host.post(ENDPOINT, cxt)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 113, in post
    return self._handle(request)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 54, in _handle
    raise NotFound(response)
tinychain.error.NotFound: {'/error/not_found': 'while resolving z: /exp'}

======================================================================
ERROR: testImag (tctest.client.test_complex.ComplexNumberOpsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mustafa/git/tc/tests/tctest/client/test_complex.py", line 28, in testImag
    actual = self.host.post(ENDPOINT, cxt)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 113, in post
    return self._handle(request)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 54, in _handle
    raise NotFound(response)
tinychain.error.NotFound: {'/error/not_found': 'while resolving z: /imag'}

======================================================================
ERROR: testReal (tctest.client.test_complex.ComplexNumberOpsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mustafa/git/tc/tests/tctest/client/test_complex.py", line 19, in testReal
    actual = self.host.post(ENDPOINT, cxt)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 113, in post
    return self._handle(request)
  File "/home/mustafa/git/tc/client/tinychain/host.py", line 54, in _handle
    raise NotFound(response)
tinychain.error.NotFound: {'/error/not_found': 'while resolving z: /real'}

======================================================================
FAIL: testAbs (tctest.client.test_complex.ComplexNumberOpsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mustafa/git/tc/tests/tctest/client/test_complex.py", line 56, in testAbs
    self.assertEqual(actual, abs(n))
AssertionError: 25 != 5.0

----------------------------------------------------------------------
Ran 14 tests in 0.099s

FAILED (failures=1, errors=5)
```

**Comment by haydnv** [comment]
The main Dockerfile installs the latest release, not the latest commit. There's a separate Dockerfile in the `tests` directory that's used by `tests.apps` but I updated `tests.client` to use it as well. You should now see all the tests pass if you run

```
export TC_HOST=http://127.0.0.1:8702
python3 -m tests.tctest.client -k Complex
```

(no need for `docker run`, that will happen automatically)

**Pull request merged**
